name = "Oogacraft"
author = "AshyBoxy"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "068e3354a79c0e0ceaee6155861eb88957cea307630b3bc751d6c86e9a7d972d"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
datapack-folder = "config/paxi/datapacks"
