name = "Oogacraft"
author = "AshyBoxy"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d0cb0df13a8fac65af6fe0495ef4dae0cc9165fca2075f2ff1f0adfd0c262d9"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
