name = "Oogacraft"
author = "AshyBoxy"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "381a1986f2349efb64491c9d9d1e1b3ea628717f2f23017baffeb172d4d4ccb7"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
