name = "Oogacraft"
author = "AshyBoxy"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a45e69bafcac8d3f7b08c1a345da59be74e96b5b738c2d3433c49cbe66369e90"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
