name = "Oogacraft"
author = "AshyBoxy"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca42d808903b9d428294d5443b29a8a2e2b31065f1536a4f92eae70a968ed4b8"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
