name = "Oogacraft"
author = "AshyBoxy"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea7db0edb2715cad45920b2b1dea55e23b7d629e339c8ff980c8bd6038287d96"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
datapack-folder = "config/paxi/datapacks"
