#Preferences for outputs from tags used in automatic compat in recipes
tagPreferences = ["minecraft", "kubejs", "crafttweaker", "croptopia", "create", "tconstruct", "techreborn", "modern_industrialization", "indrev"]
